# This is the location of the bot's token. The token must be placed on
# the first line of the file
token_file: config/token.txt

# These are the people the bot DMs when something goes wrong
# Add yourself here if you want to know when something goes wrong
developers:
  - 240995021208289280

# It's the prefix.. What more do I need to say?
command_prefix: "!"

# The cogs to load when the bot starts
cogs:
  - cogs.misc
  - cogs.git
  - cogs.core
